[project]
name = "long-horizon-execution"
version = "0.1.0"
description = "Inspect integration of 'The Illusion of Diminishing Return: Measuring Long Horizon Execution in LLMs'"
authors = [{ name = "Sam Deverett" }]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "anthropic>=0.68.1",
    "inspect-ai>=0.3.134",
    "openai>=1.109.1",
]

[dependency-groups]
dev = [
    "mypy>=1.9.0,<2",
    "ruff>=0.6.0,<0.7",
    "types-pyyaml>=6.0.12,<7",
]
optional = [
    "aisitools",
]

[tool.ruff.lint]
select = ["E",   # pycodestyle errors
          "W",   # pycodestyle warnings
          "F",   # flake8
          "D",   # pydocstyle
          "I",   # isort
        ]
ignore = ["E203", "D10", "D203", "D212"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.uv.sources]
aisitools = { git = "ssh://git@github.com/AI-Safety-Institute/aisi-inspect-tools.git" }
